//! Transparent routing (Linux): force **all** TCP from the shell through the
//! WARP SOCKS port — not just proxy-aware tools.
//!
//! This works by preloading `libproxychains` into the shell (so every child
//! process has its `connect()` hooked and redirected to our SOCKS5 front) via a
//! generated proxychains config. Unlike the env-var path (which tools may
//! ignore), this catches proxy-unaware programs too.
//!
//! It is Linux-only for now (`LD_PRELOAD`); macOS restricts `DYLD_INSERT_LIBRARIES`
//! under SIP, and Windows needs a different mechanism.

use std::path::Path;

use anyhow::Result;

/// Render a proxychains config that routes everything through `127.0.0.1:port`
/// with remote DNS (no leak).
pub fn proxychains_config(socks_port: u16) -> String {
    format!(
        "# generated by warpterm — route all TCP through the WARP front SOCKS5\n\
         strict_chain\n\
         quiet_mode\n\
         proxy_dns\n\
         tcp_read_time_out 15000\n\
         tcp_connect_time_out 8000\n\
         [ProxyList]\n\
         socks5 127.0.0.1 {socks_port}\n"
    )
}

/// Write the proxychains config to `config_path` and return the env vars that
/// enable transparent routing for a shell spawned with them.
pub fn transparent_env(socks_port: u16, config_path: &Path) -> Result<Vec<(String, String)>> {
    #[cfg(target_os = "linux")]
    {
        std::fs::write(config_path, proxychains_config(socks_port))?;
        Ok(vec![
            ("LD_PRELOAD".to_string(), libproxychains()),
            (
                "PROXYCHAINS_CONF_FILE".to_string(),
                config_path.display().to_string(),
            ),
        ])
    }
    #[cfg(not(target_os = "linux"))]
    {
        let _ = (socks_port, config_path);
        anyhow::bail!("transparent routing is currently Linux-only (LD_PRELOAD)")
    }
}

/// Locate the `libproxychains` shared object (falls back to the soname, resolved
/// via the linker cache).
#[cfg(target_os = "linux")]
fn libproxychains() -> String {
    for p in [
        "/lib/x86_64-linux-gnu/libproxychains.so.4",
        "/usr/lib/x86_64-linux-gnu/libproxychains.so.4",
        "/usr/lib/libproxychains4.so",
        "/usr/lib/x86_64-linux-gnu/libproxychains4.so",
    ] {
        if Path::new(p).exists() {
            return p.to_string();
        }
    }
    "libproxychains.so.4".to_string()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn config_has_socks_line() {
        let cfg = proxychains_config(1080);
        assert!(cfg.contains("socks5 127.0.0.1 1080"));
        assert!(cfg.contains("proxy_dns")); // DNS through the proxy (no leak)
        assert!(cfg.contains("[ProxyList]"));
    }
}
